### ISSUE TITLE
Roadmap v5

### ISSUE THREAD

**Issue by TrySound** [mjmlio/mjml#1947]
- [ ] split mjml and mjml-cli - my team only consume mjml2html function from mjml package and does not use cli which adds a lot of dependencies
- [ ] drop mjml-migrate
- [ ] move html-minifier and js-beautify to cli - both adds a lot of dependencies to mjml package, would be good to let non-cli users add for example prettier and no minifier without bloating node_modules
- [x] support browser targets

**Comment by iRyusa** [comment]
> split mjml and mjml-cli - my team only consume mjml2html function from mjml package and does not use cli which adds a lot of dependencies

I'm not sure about this one, `mjml` package should remain the default package to have the full experience, you can still just target core + every other dependencies manually and register components manually here ?

> move html-minifier and js-beautify to cli

May be we should move that part on its own package and let user requires it with .mjmlconfig ?

**Comment by TrySound** [comment]
Sure, any option would be good

**Comment by HansUXdev** [comment]
Is an official roadmap for V5?

**Comment by dmgawel** [comment]
After separating mjml-cli (with minifier and beatuifier) it should be much easier to support browser targets, which I kindly ask to add for v5 roadmap. In-browser email builders with bundled mjml (instead of using API) are a perfect use-case for that.

**Comment by rootwork** [comment]
Is this why there's both `mjml` and `mjml-cli` on npm?

https://www.npmjs.com/package/mjml
https://www.npmjs.com/package/mjml-cli

That really confused me when I went looking to install it and saw references to "the cli".

They have different dependencies, but the readme for the `mjml-cli` npm package seems to just be a different version of the readme for `mjml`. It uses `mjml` throughout, instead of `mjml-cli` (including for the installation!) -- but if you have `mjml-cli` you'd have to run things like `mjml-cli input.mjml`, not `mjml input.mjml`, right?

Or is the npm `mjml-cli` package just a placeholder for now?

**Comment by iRyusa** [comment]
Forgot to reply @rootwork `mjml` is the "community" package where everything is setup to have the standard lib working (bundling the cli + std components). `mjml` package have an extra binary that register every components before passing everything to `mjml-cli`.

`mjml-cli` rely on `mjml-core` but not on `mjml` package.

**Comment by CanRau** [comment]
proper browser support would be amazing as this should enable easier use in Cloudflare Workers I guess 🤞🏼

**Comment by dmgawel** [comment]
@CanRau client-side support was added in v4, you can use it now: https://github.com/mjmlio/mjml#client-side-in-browser via official [mjml-browser](https://www.npmjs.com/package/mjml-browser) package.

**Comment by olup** [comment]
But this rely on the browser abstraction, like `window`, not available in cf worker for instance

**Comment by danawoodman** [comment]
Is v5 abandoned? Would really love to use mjml on CloudFlare Workers

**Comment by frederichoule** [comment]
Currently, [v5.0.0-alpha.6](https://github.com/mjmlio/mjml/releases/tag/v5.0.0-alpha.6) doesn’t work in Cloudflare Workers due to its reliance on node dependencies.

**Comment by dazgreer** [comment]
Closing as the points here have largely either been addressed, moved or superceded. 

`mjml-browser` was addressed in the full MJML `5.0.0` release

Please open a new issue to discuss anything remaining from this issue
